"""

Revision ID: 569a62bb0b10
Revises: 87567c57b75e
Create Date: 2025-12-28 01:36:18.848093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569a62bb0b10'
down_revision: Union[str, None] = '87567c57b75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('clients', 'created_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'created_at')
    # ### end Alembic commands ###
