"""

Revision ID: 87567c57b75e
Revises: 45eed663166a
Create Date: 2025-12-28 00:51:32.408485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87567c57b75e'
down_revision: Union[str, None] = '45eed663166a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_banks_bik_unique', table_name='banks')
    # Add client_type as nullable first, set default for existing rows, then make NOT NULL
    op.add_column('clients', sa.Column('client_type', sa.String(length=10), nullable=True))
    op.execute("UPDATE clients SET client_type = 'ip' WHERE client_type IS NULL")
    op.alter_column('clients', 'client_type', nullable=False)
    op.add_column('clients', sa.Column('short_name', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('ogrn', sa.String(length=15), nullable=True))
    op.add_column('clients', sa.Column('kpp', sa.String(length=9), nullable=True))
    op.add_column('clients', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('acting_basis', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('passport_series', sa.String(length=4), nullable=True))
    op.add_column('clients', sa.Column('passport_number', sa.String(length=6), nullable=True))
    op.add_column('clients', sa.Column('passport_issued_by', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('passport_issued_date', sa.Date(), nullable=True))
    op.alter_column('clients', 'inn',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('clients', 'settlement_account',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('clients', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'patronymic',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('clients', 'ogrnip')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add ogrnip as nullable first, set default for existing rows, then make NOT NULL
    op.add_column('clients', sa.Column('ogrnip', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.execute("UPDATE clients SET ogrnip = '' WHERE ogrnip IS NULL")
    op.alter_column('clients', 'ogrnip', nullable=False)
    op.alter_column('clients', 'patronymic',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('clients', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'settlement_account',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clients', 'inn',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.drop_column('clients', 'passport_issued_date')
    op.drop_column('clients', 'passport_issued_by')
    op.drop_column('clients', 'passport_number')
    op.drop_column('clients', 'passport_series')
    op.drop_column('clients', 'acting_basis')
    op.drop_column('clients', 'position')
    op.drop_column('clients', 'kpp')
    op.drop_column('clients', 'ogrn')
    op.drop_column('clients', 'company_name')
    op.drop_column('clients', 'short_name')
    op.drop_column('clients', 'client_type')
    op.create_index('ix_banks_bik_unique', 'banks', ['bik'], unique=True)
    # ### end Alembic commands ###
