/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Banks */
        get: operations["get_banks_api_banks_get"];
        put?: never;
        /** Create Bank */
        post: operations["create_bank_api_banks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/{bank_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bank */
        get: operations["get_bank_api_banks__bank_id__get"];
        /** Update Bank */
        put: operations["update_bank_api_banks__bank_id__put"];
        post?: never;
        /** Delete Bank */
        delete: operations["delete_bank_api_banks__bank_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/import-cbr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import From Cbr
         * @description Import bank directory from Central Bank of Russia.
         */
        post: operations["import_from_cbr_api_banks_import_cbr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Services */
        get: operations["get_services_api_services_get"];
        put?: never;
        /** Create Service */
        post: operations["create_service_api_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Service */
        get: operations["get_service_api_services__service_id__get"];
        /** Update Service */
        put: operations["update_service_api_services__service_id__put"];
        post?: never;
        /** Delete Service */
        delete: operations["delete_service_api_services__service_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clients */
        get: operations["get_clients_api_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_clients__client_id__get"];
        /** Update Client */
        put: operations["update_client_api_clients__client_id__put"];
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_api_clients__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client Contracts
         * @description Получить список договоров клиента
         */
        get: operations["get_client_contracts_api_clients__client_id__contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contracts */
        get: operations["get_contracts_api_contracts_get"];
        put?: never;
        /** Create Contract */
        post: operations["create_contract_api_contracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["get_contract_api_contracts__contract_id__get"];
        /** Update Contract */
        put: operations["update_contract_api_contracts__contract_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{contract_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Contract */
        get: operations["download_contract_api_contracts__contract_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{contract_id}/download-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Contract Pdf */
        get: operations["download_contract_pdf_api_contracts__contract_id__download_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BankCreate */
        BankCreate: {
            /** Name */
            name: string;
            /** Bik */
            bik: string;
            /** Correspondent Account */
            correspondent_account: string;
        };
        /** BankListResponse */
        BankListResponse: {
            /** Items */
            items: components["schemas"]["BankResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /** BankResponse */
        BankResponse: {
            /** Name */
            name: string;
            /** Bik */
            bik: string;
            /** Correspondent Account */
            correspondent_account: string;
            /** Id */
            id: number;
        };
        /** BankUpdate */
        BankUpdate: {
            /** Name */
            name: string;
            /** Bik */
            bik: string;
            /** Correspondent Account */
            correspondent_account: string;
        };
        /** CBRImportResult */
        CBRImportResult: {
            /** Success */
            success: boolean;
            /** Total Processed */
            total_processed: number;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Errors */
            errors: number;
            /**
             * Error Messages
             * @default []
             */
            error_messages: string[];
            /**
             * Import Date
             * Format: date-time
             */
            import_date: string;
        };
        /** ClientCreate */
        ClientCreate: {
            /**
             * Client Type
             * @default ip
             * @enum {string}
             */
            client_type: "ip" | "ooo" | "ao" | "pao" | "nko" | "fl";
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Ogrn */
            ogrn?: string | null;
            /** Inn */
            inn?: string | null;
            /** Kpp */
            kpp?: string | null;
            /** Address */
            address: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Settlement Account */
            settlement_account?: string | null;
            /** Bank Id */
            bank_id?: number | null;
            /** Last Name */
            last_name: string;
            /** First Name */
            first_name: string;
            /** Patronymic */
            patronymic?: string | null;
            /** Position */
            position?: string | null;
            /** Acting Basis */
            acting_basis?: string | null;
            /** Passport Series */
            passport_series?: string | null;
            /** Passport Number */
            passport_number?: string | null;
            /** Passport Issued By */
            passport_issued_by?: string | null;
            /** Passport Issued Date */
            passport_issued_date?: string | null;
        };
        /** ClientListResponse */
        ClientListResponse: {
            /** Items */
            items: components["schemas"]["ClientResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /** ClientResponse */
        ClientResponse: {
            /**
             * Client Type
             * @default ip
             * @enum {string}
             */
            client_type: "ip" | "ooo" | "ao" | "pao" | "nko" | "fl";
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Ogrn */
            ogrn?: string | null;
            /** Inn */
            inn?: string | null;
            /** Kpp */
            kpp?: string | null;
            /** Address */
            address: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Settlement Account */
            settlement_account?: string | null;
            /** Bank Id */
            bank_id?: number | null;
            /** Last Name */
            last_name: string;
            /** First Name */
            first_name: string;
            /** Patronymic */
            patronymic?: string | null;
            /** Position */
            position?: string | null;
            /** Acting Basis */
            acting_basis?: string | null;
            /** Passport Series */
            passport_series?: string | null;
            /** Passport Number */
            passport_number?: string | null;
            /** Passport Issued By */
            passport_issued_by?: string | null;
            /** Passport Issued Date */
            passport_issued_date?: string | null;
            /** Id */
            id: number;
            bank?: components["schemas"]["BankResponse"] | null;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /**
             * Client Type
             * @default ip
             * @enum {string}
             */
            client_type: "ip" | "ooo" | "ao" | "pao" | "nko" | "fl";
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Ogrn */
            ogrn?: string | null;
            /** Inn */
            inn?: string | null;
            /** Kpp */
            kpp?: string | null;
            /** Address */
            address: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Settlement Account */
            settlement_account?: string | null;
            /** Bank Id */
            bank_id?: number | null;
            /** Last Name */
            last_name: string;
            /** First Name */
            first_name: string;
            /** Patronymic */
            patronymic?: string | null;
            /** Position */
            position?: string | null;
            /** Acting Basis */
            acting_basis?: string | null;
            /** Passport Series */
            passport_series?: string | null;
            /** Passport Number */
            passport_number?: string | null;
            /** Passport Issued By */
            passport_issued_by?: string | null;
            /** Passport Issued Date */
            passport_issued_date?: string | null;
        };
        /** ContractCreate */
        ContractCreate: {
            /** Number */
            number: string;
            /** Client Id */
            client_id: number;
            /** Contract Date */
            contract_date?: string | null;
            /** Service Ids */
            service_ids: number[];
        };
        /** ContractListResponse */
        ContractListResponse: {
            /** Items */
            items: components["schemas"]["ContractResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /** ContractResponse */
        ContractResponse: {
            /** Id */
            id: number;
            /** Number */
            number: string;
            /** Client Id */
            client_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            client?: components["schemas"]["ClientResponse"] | null;
            /**
             * Services
             * @default []
             */
            services: components["schemas"]["ServiceResponse"][];
        };
        /** ContractUpdate */
        ContractUpdate: {
            /** Number */
            number: string;
            /** Client Id */
            client_id: number;
            /** Contract Date */
            contract_date?: string | null;
            /** Service Ids */
            service_ids: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** ServiceCreate */
        ServiceCreate: {
            /** Name */
            name: string;
            /** Price */
            price: number | string;
            /** Payment Terms */
            payment_terms: string;
        };
        /** ServiceListResponse */
        ServiceListResponse: {
            /** Items */
            items: components["schemas"]["ServiceResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
        };
        /** ServiceResponse */
        ServiceResponse: {
            /** Name */
            name: string;
            /** Price */
            price: string;
            /** Payment Terms */
            payment_terms: string;
            /** Id */
            id: number;
        };
        /** ServiceUpdate */
        ServiceUpdate: {
            /** Name */
            name: string;
            /** Price */
            price: number | string;
            /** Payment Terms */
            payment_terms: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_banks_api_banks_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bank_api_banks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bank_api_banks__bank_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bank_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bank_api_banks__bank_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bank_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bank_api_banks__bank_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bank_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_from_cbr_api_banks_import_cbr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CBRImportResult"];
                };
            };
        };
    };
    get_services_api_services_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_service_api_services_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_service_api_services__service_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_service_api_services__service_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_service_api_services__service_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clients_api_clients_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_clients__client_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_contracts_api_clients__client_id__contracts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contracts_api_contracts_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contract_api_contracts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_api_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contract_api_contracts__contract_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_contract_api_contracts__contract_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_contract_pdf_api_contracts__contract_id__download_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
